apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h6qzz2vvi-go 
  janus-idp.io/tekton: h6qzz2vvi-go
  backstage.io/kubernetes-id: h6qzz2vvi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h6qzz2vvi-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  